Added algorithm for finding cycle in undirected graph
siddharth25pandey/CPP-Programming pull request #157
Opened 2020-10-04 15:39 UTC by anand4234

2020-10-04 17:58 UTC, siddharth25pandey requested changes
@anand4234 Do the changes as suggested.
Thanks!

2020-10-04 17:58 UTC, siddharth25pandey commented on Graph Algorithm/detect_cycle_ug.cpp
> +};
Take Dynamic Input from the user

2020-10-04 17:58 UTC, siddharth25pandey commented on Graph Algorithm/detect_cycle_ug.cpp
> +#include<set>
Use single header file **bits/stc++**

2020-10-04 17:58 UTC, siddharth25pandey commented on Graph Algorithm/detect_cycle_ug.cpp
> +#define NODE 5
Take input from the user

2020-10-05 17:23 UTC, anand4234 commented
@siddharth25pandey I've changed the code to take graph nodes as input.

2020-10-14 07:04 UTC, anand4234 commented
Hi @siddharth25pandey I've added Kruskal algorithm also ..pls review

2020-12-21 02:12 UTC, closed without merging